stages:
  build_brick:
    cmd: python3 stages_v2/download_and_process_baseline.py --workers 4 --output-dir brick/pubmed.parquet
    deps:
      - stages_v2/download_and_process_baseline.py
    outs:
      - brick/pubmed.parquet
