stages:
  download_dtd:
    cmd: wget -P ./download/pubmed http://dtd.nlm.nih.gov/ncbi/pubmed/out/pubmed_190101.dtd
    outs:
      - ./download/pubmed/pubmed_190101.dtd
  download_pubmed:
    cmd: wget -r -m -P ./download ftp://ftp.ncbi.nlm.nih.gov/pubmed
    deps:
      - ./download/pubmed/pubmed_190101.dtd
    outs:
      - download/ftp.ncbi.nlm.nih.gov:
          persist: true
          cache: true
  process_pubmed_json:
    cmd: Rscript R/process.R
    deps:
      - R/process.R
      - download/ftp.ncbi.nlm.nih.gov
    outs:
      - brick/pubmed.parquet:
          persist: true
          cache: true